fos_user_security:
    resource: "@UserBundle/Resources/config/routing/security.yml"

fos_user_profile:
    resource: "@UserBundle/Resources/config/routing/profile.yml"
    prefix: /profile

fos_user_register:
    resource: "@UserBundle/Resources/config/routing/registration.yml"
    prefix: /register

fos_user_resetting:
    resource: "@UserBundle/Resources/config/routing/resetting.yml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile