parameters:
#    user.example.class: Boutcaz\UserBundle\Example

services:
    fos_user.registration.form.type:
        class: Boutcaz\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fos_user_registration }
    fos_user.profile.form.type:
        class: Boutcaz\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fos_user_profile }
