<?php

namespace Boutcaz\BoutiqueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{	
	public function getAllAnnonces()
	{
		$qb = $this->createQueryBuilder('a')
                   ->select('a,b,c')
                   ->leftJoin('a.categorie', 'b')
                   ->leftJoin('a.auteurtype', 'c')
                   ->orderBy('a.date', 'DESC')
                   ->addSelect('a.id,a.date,a.titre,a.description,a.tarif,b.categorie,a.auteurid,c.type');
                   
                   return $qb->getQuery()->getResult();
	}
}
