<?php

namespace Boutcaz\BoutiqueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{	
	public function getAllAnnonces()
	{
		$qb = $this->createQueryBuilder('a')
                   ->select('a,b,c')
                   ->leftJoin('a.categorie', 'b')
                   ->leftJoin('a.auteurtype', 'c')
                   ->orderBy('a.date', 'DESC')
                   ->addSelect('a.id,a.date,a.titre,a.description,a.tarif,b.categorie,a.auteurid,c.type');
                   
                   return $qb->getQuery()->getResult();
	}
	
	public function countResult($value)
	{
		return $this->createQueryBuilder('a')
					->select('count(a)')
					->where('a.region = :region' )
					->setParameter('region', $value)
					->getQuery()
					->getSingleScalarResult();
	}
	
	public function findAnnonces($value)
	{
		return $this->createQueryBuilder('a')
					->where('a.titre LIKE :value')
					->OrWhere('a.description LIKE :value')
					->setParameter('value', '%'.$value.'%')
					->getQuery()
					->getResult();
	}
	
	//====================================================================================
	//! Fonction pour retrouver toutes les annonces des membres et des Invités réunies
	//====================================================================================
	


	
}
