<?php

namespace Boutcaz\BoutiqueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
	public function getListCategories()
	{
		$qb = $this->createQueryBuilder('a')
				   ->select('a','b')
				   ->leftjoin('a.parentcategorie','b')
				   ->addSelect('a.categorie, b.parent');
				   
				  return $qb->getQuery()->getResult();
				   
	}
}
