<?php

namespace Boutcaz\BoutiqueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestAnnonceRepository extends EntityRepository
{	
	public function countResult($value)
	{
		return $this->createQueryBuilder('a')
					->select('count(a)')
					->where('a.region = :region' )
					->setParameter('region', $value)
					->getQuery()
					->getSingleScalarResult();
	}
	
	public function findAnnonces($value)
	{
		return $this->createQueryBuilder('a')
					->where('a.titre LIKE :value')
					->OrWhere('a.description LIKE :value')
					->setParameter('value', '%'.$value.'%')
					->getQuery()
					->getResult();
	}
}
