<?php

namespace Boutcaz\BoutiqueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository
{
	public function getAlllist()
	{
		$query = $this->createQueryBuilder('a')
					   ->select('a');
					   
					   return $query->getQuery()->getResult();
	}
	
}
