boutique_homepage:
    pattern:  /
    defaults: { _controller: BoutiqueBundle:Boutique:index }

region_homepage:
    pattern:  /region/{slug}
    defaults: { _controller: BoutiqueBundle:Boutique:region }

region_check:
    pattern:  /region_check
    defaults: { _controller: BoutiqueBundle:Boutique:regionCheck }   

show_homepage:
    pattern:  /show/{region}/{departement}/{ville}/{id}/{slug}
    defaults: { _controller: BoutiqueBundle:Boutique:show }

deposer_homepage:
    pattern:  /deposer
    defaults: { _controller: BoutiqueBundle:Boutique:deposer }
