parameters:
#    boutique.example.class: Boutcaz\BoutiqueBundle\Example

services:
#    boutique.example:
#        class: %boutique.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
