Boutcaz\BoutiqueBundle\Entity\Annonce:
    properties:
        titre:
            - Length: { min:3 }
            - Regex:  { pattern: "/^[a-zA-Z0-9àáâãäåòóôõöøèéêëçìíîïùúûüÿñ -]+$/", message:"- Votre titre comporte des caractéres interdits" }
        tarif:
            - Regex: { pattern: "/\d/", message:"- Le tarif ne peut contenir que des chiffres"}
        ipadress:
            - Ip: